# Generated by Django 5.0.6 on 2024-08-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-31 15:06:32.394049'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pro',
            field=models.ManyToManyField(related_name='my_product', to='kh.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='css/'),
        ),
    ]
