# Generated by Django 5.0.6 on 2024-08-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0002_product_created_at_product_pro_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro',
        ),
    ]
