# Generated by Django 5.0.6 on 2024-08-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0003_remove_product_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
