# Generated by Django 5.0.6 on 2024-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0004_remove_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-31 15:06:32.394049'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pro',
            field=models.ManyToManyField(related_name='my_product', to='kh.user'),
        ),
    ]
