# Generated by Django 5.0.6 on 2024-08-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0005_product_created_at_product_pro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
