# Generated by Django 5.0.6 on 2024-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='css/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_product', models.IntegerField()),
                ('pro', models.ManyToManyField(related_name='my_product', to='kh.user')),
            ],
        ),
    ]
