# Generated by Django 5.0.6 on 2024-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
