# Generated by Django 5.0.6 on 2024-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.FloatField(default='20.0'),
            preserve_default=False,
        ),
    ]
